name: Windows Build

on:
  push:
    branches: [ main, unit-tests ]
  pull_request:
    branches: [ main, unit-tests ]

jobs:
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build production
      run: npm run electron:build
      
    - name: Verify build artifacts
      run: |
        echo "Checking release directory..."
        dir release\
        echo "Build completed successfully!"
